### ISSUE TITLE
Feature-request - Adding Avira virus scanner

### ISSUE THREAD

**Issue by croessner** [vstakhov/rspamd#1063]
I have seen this page:

https://rspamd.com/doc/modules/antivirus.html

Do you plan on adding Avira SAVAPI-support? That would be awesome :-)

**Comment by fatalbanana** [comment]
That should be doable. Difficulties with adding new scanners are generally about getting hands on the software and possibly protocol documentation. In this case it seems the software is not readily downloadable and I could find no protocol documentation- however there is support in Amavis which could be used as reference. I'd be interested to know if savapi supports pipelining and if we could stream a message at it rather than pointing it to message parts on disk.

**Comment by croessner** [comment]
As far as I can remember, you can not stream something to savapi. I wrote the savacli client. Feel free to contact me directly: c@roessner.co

**Comment by vstakhov** [comment]
What is the conclusion on this issue?

**Comment by croessner** [comment]
Good question. I really would love Avira support :-)

**Comment by croessner** [comment]
Normally using the savapi is trivial.

Connecting to the savapi-socket, then:

SET PRODUCT 12345
SET SCAN_MODE ALL
SCAN /path/to/file/for/scanning

That is all. Of course, the protocol understand more than these, but in short this is, what needs to be done.

**Comment by croessner** [comment]
https://github.com/sys4/savacli/blob/master/savacli

Look at the Protocol class for example

**Comment by croessner** [comment]
I have written this scanner in python

**Comment by fatalbanana** [comment]
This could be closed I suppose.
