### ISSUE TITLE
RCVD_NO_TLS_LAST(0.00)[]

### ISSUE THREAD

**Issue by xpunkt** [vstakhov/rspamd#1587]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

github head

### Additional information:

Received: from english-breakfast.cloud9.net (english-breakfast.cloud9.net [168.100.1.7])
	by example.org (Postfix) with ESMTPS id D0CD61BE135
	for <user@example.org>; Thu, 13 Apr 2017 02:21:00 +0100 (BST)

ESMTPS is TLS

**Comment by smfreegard** [comment]
Full headers required.   And details of how rspamd is being called.  

RCVD_NO_TLS_LAST is only fired when the last (current) Recevied hop doesn't use TLS and this works for me.   It might not work correctly if whatever is calling rspamd adds it's own headers after rspamd has finished running.

**Comment by vstakhov** [comment]
Received: from mx2.slc.paypal.com (mx0.slc.paypal.com [173.0.84.225])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail.highsecure.ru (Postfix) with ESMTPS id 1DE09300469
	for <support@rspamd.com>; Sun, 16 Apr 2017 12:53:47 +0200 (CEST)
Received: (qmail 8715 invoked by uid 993); 16 Apr 2017 10:53:37 -0000
Date: Sun, 16 Apr 2017 03:53:37 -0700

**Comment by vstakhov** [comment]
I think it is related to Rmilter artificial Received added to a message.

**Comment by heraklit256** [comment]
I am actually experiencing the same (running rspamd 1.6.6 as a milter with postfix): Mails are delivered to my mailserver via ESMTPS, however, in the rspamd results it says: RCVD_NO_TLS_LAST(0.00)[]

Here are the Received headers of one mail where this happens:

     Received: from mx1.riseup.net (mx1.riseup.net [198.252.153.129])
		(using TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits))
		(Client CN "*.riseup.net", Issuer "COMODO RSA Domain Validation Secure Server CA" (verified OK))
		by mx-nbg.link38.eu (Postfix) with ESMTPS id 96842371BB4
		for <[REDACTED]@link38.eu>; Wed, 28 Mar 2018 15:37:33 +0200 (CEST)
     Received: from cotinga.riseup.net (cotinga-pn.riseup.net [10.0.1.164])
		(using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
		(Client CN "*.riseup.net", Issuer "COMODO RSA Domain Validation Secure Server CA" (verified OK))
		by mx1.riseup.net (Postfix) with ESMTPS id CA2231A08A9
		for <[REDACTED]@link38.eu>; Wed, 28 Mar 2018 06:37:23 -0700 (PDT)
Thank you very much.

**Comment by smfreegard** [comment]
>  rspamd 1.6.6 

Which is old - upgrade and then raise a new issue if this is still a problem.

**Comment by heraklit256** [comment]
Currently trying to do so (see https://github.com/HardenedBSD/hardenedBSD/issues/298)...

**Comment by kroerig** [comment]
Hello,

i have to reopen this issue because I also get RCVD_NO_TLS_LAST (0.1) with outgoing mails.

Rspamd: 2.2-1~bionic

Header:

`Return-Path: <bp-admin@XXXXXXXXXXXXXXX.de>
X-Original-To: info@XXXXXXXXXXXXXX
Delivered-To: klaus@XXXXXXXXXXXXXXXXXX
Received: from mail.XXXXXXXXXXXXXXXXXX.de (mail.XXXXXXXXXXXXXXXXXXX.de [80.152.239.XXX])
	by liveconfig01.XXXXXXXXXXX.net (Postfix) with ESMTPS id 2A1DA1C0B42
	for <info@XXXXXXXXXXX>; Sun,  5 Jan 2020 21:44:29 +0100 (CET)
Authentication-Results: liveconfig01.XXXXXXXXXX.net;
	dkim=pass (2048-bit key; unprotected) header.d=XXXXXXXXXX.de header.i=@XXXXXXXXXXXXX.de header.b=VVFViU2v;
	dkim-atps=neutral
Received: from bp01ex01.sbskanzlei.local (bp01ex01.sbskanzlei.local [192.168.15.53])
	by mail.XXXXXXXXXXXXXXXX.de (Postfix) with ESMTPSA id 9073E8C61
	for <info@XXXXXXXXXXXXXX.de>; Sun,  5 Jan 2020 20:44:28 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=XXXXXXXXXXXX.de;
	s=2020-01; t=1578257068;
	h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 content-transfer-encoding:content-transfer-encoding:
	 in-reply-to:in-reply-to:references:references;
	bh=qZLjVwh0yTY9ikYPHeauE+HCgFuc85XTm8gpSQnU0Wk=;
	b=VVFViU2vx7UJiPRpHRl2wg4bsYCxWIBwA6KN/YH6qqW4FdGbYslmOVMo7YcByj6hM2vF3Y
	qbhtaQW6D0Dj4BFjpDN7+k4sj0rLS6DvzFvVgalRRu57PrrqOkMQwXfOfHJWhQARZkwzv7
	utevPW3TLV+2jzSJaVQ3J4JoqoeOhc76EDOETNvlyak28dFDT86Ow7SZptUrU3VC51xgHe
	BVUBPdiqgycL9nag9MCy5pIDPp/ZcKVr2LvWU83FnVcjDFHCX632B77FbnWOFFt+LMtSg7
	kg4sJQBJZU1+k/nwH5e8QDyiQz4OqzljSEnRqie0GB9oN4JLC1xUFkiOjMKd6w==
Received: from bp01ex01.sbskanzlei.local (192.168.15.53) by
 bp01ex01.sbskanzlei.local (192.168.15.53) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.2.529.5;
 Sun, 5 Jan 2020 21:44:37 +0100
Received: from bp01ex01.sbskanzlei.local ([fe80::f887:659d:c997:21d4]) by
 bp01ex01.sbskanzlei.local ([fe80::f887:659d:c997:21d4%4]) with mapi id
 15.02.0529.005; Sun, 5 Jan 2020 21:44:36 +0100
`
Symbols:
`REPLY (-4)
RCVD_NO_TLS_LAST (0.1)
MIME_GOOD (-0.1) [text/plain]
DKIM_SIGNED (0)
ARC_NA (0)
MIME_TRACE (0) [0:+]
HAS_XOIP (0)
TO_DN_ALL (0)
FROM_HAS_DN (0)
RCPT_COUNT_ONE (0) [1]
FROM_EQ_ENVFROM (0)
TO_MATCH_ENVRCPT_ALL (0)
RCVD_COUNT_TWO (0) [2]
MID_RHS_MATCH_FROM (0)
`

I checked logfiles on every host. All connections were secured by TLS.
