### ISSUE TITLE
Can't disable DKIM signing

### ISSUE THREAD

**Issue by wociscz** [vstakhov/rspamd#1774]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [X] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3, using rspamd_proxy without rmilter
### Operation system, CPU, memory and environment:
ubuntu server 16.04.2 64bit, some dell poweredge server
### Description (Please provide a descriptive summary of the issue):
Can't disable  DKIM signing. I need to rspamd be only in "veryfier" role. 
Tried to put these to local.d/dkim_signing.conf:
```
auth_only = false;
sign_local = false;
sign_networks = "/etc/rspamd/local.d/localhost.inc";
```
localhost.inc contain only 127.0.0.1

But after rspamd restart - there are still `(rspamd_proxy) <a8009f>; proxy; lua_dkim_sign_handler: cannot load dkim key..` messages in syslog. So rspamd still trying to load keys for domains and trying to sign?

Is there some official way to enable only dkim verification and disable signing?

regards, Jan

**Comment by fatalbanana** [comment]
You can set `enabled = false` in `dkim_signing` configuration to turn the module off completely. Since ARC module provides both signing & validation, you probably want to disable signing **only** by disabling `ARC_SIGNED` symbol somehow, for example by adding a condition like below to `/etc/rspamd/rspamd.local.lua` or using [settings](https://rspamd.com/doc/configuration/settings.html):

~~~
rspamd_config:add_condition('ARC_SIGNED', function(task) return false end)
~~~

**Comment by wociscz** [comment]
Thanks, enabled = false; in override.d/dkim_singing.conf works like i want.
