### ISSUE TITLE
Rspamd should have a Lua API for identifying effective TLD parts of domains

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#179]
This could use data from Mozilla's public suffix list: https://publicsuffix.org

**Comment by awhitesong** [comment]
I am working on this issue. I am bit unsure about the structure of its implementation in the library. Should i write this in C using the lua library and include it in /src/lua or where otherwise. 
I have written a working prototype in Lua which is extracting the TLD from public suffix list though. Where should i be including it? Thanks.

**Comment by vstakhov** [comment]
That should be done in libutil/url.c and libutil/url.h We need to convert static structures to the loadable trie of suffixes (aho-corasic is implemented in libutil/trie.c). That's not an easy task btw.

**Comment by awhitesong** [comment]
Ok. Meanwhile here is the current implementation link:
https://github.com/awhitesong/TLDExtract-Lua  

Will atleast try to start the implementation with url.h. Will ask if any problems, atleast having some experience in suffix tries. Thanks.
