### ISSUE TITLE
Composite Rules to Include Matches

### ISSUE THREAD

**Issue by gosney** [vstakhov/rspamd#1819]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.2

### Operation system, CPU, memory and environment:
CentOS

### Description (Please provide a descriptive summary of the issue):
It would be great for Composite Rules to include criteria that has matched in the scan results.
E.g. COMPOSITE_RULE_10 (7.50)[COMPOSITE_RULE_2, COMPOSITE_RULE_4, COMPOSITE_RULE_7]

### Expected results:
COMPOSITE_RULE_10 (7.50)[COMPOSITE_RULE_2, COMPOSITE_RULE_4, COMPOSITE_RULE_7]

### Actual results:
COMPOSITE_RULE_10 (7.50)

**Comment by vstakhov** [comment]
And what should be inserted in the following rule?

```
TEST_COMP = !SYMBOL;
```

I'm not even talking about more complicated cases with different policies mix.

**Comment by gosney** [comment]
In the above example you would insert nothing. 

We would obviously only be able to insert positive matches which is what I am interested in

**Comment by vstakhov** [comment]
The problem here is that composite rules have no understanding of the enclosing grammar. Let me show you more complicated examples:

```
!!SYMBOL
```

```
!(SYM1 || !SYM2)
```

```
SYM1|| !(SYM1 && SYM2)
```

And so on, and so forth: you just cannot understand what has triggered a specific composite. In theory, there is a traced mode of expressions parsing and I can add that. Unfortunately, it won't help a lot leading to somehow confusing results in the examples above...

**Comment by gosney** [comment]
Understood. Will close it off
