### ISSUE TITLE
ARC for forwarded mails

### ISSUE THREAD

**Issue by lukas-hetzenecker** [vstakhov/rspamd#1993]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
`1.7.0-0~git96~041d3b028~xenial`

### Description (Please provide a descriptive summary of the issue):
I have configured postfix to forward all incoming mails for my destination domain _myname.com_ to another provider, _destinationprovider.com_ .

I noticed that some senders now have a DMARC policy of p=reject. Because my mail server is just forwarding those mails to somewhere else, the SPF check now obviously fails - those mails never get delivered.

This is where I thought ARC would come to my rescue. I configured rspamd to add ARC headers.
The headers are added to mails origination from my domain, but never for mails which are forwarded.

I think this is a misconfiguration on my end, but unfortunately the ARC documentation is somewhat lacking, so I can't figure out how to get this right.

### Steps to reproduce:

1. Enable ARC in rspamd
2. Configure mail forwarding in postfix (or dovecot)

### Expected results:
ARC-Authentication-Results, ARC-Seal and ARC-Message-Signature header added to all outgoing mails.
_destinationprovider.com_  accepts all forwarded mails.

### Actual results:
No ARC headers in forwarded mails, see log message below:

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

```
2018-01-19 15:42:33 #19(normal) <df62ea>; task; spf_symbol_callback: skip SPF checks for local networks and authorized users
2018-01-19 15:42:33 #19(normal) <df62ea>; task; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
2018-01-19 15:42:33 #19(normal) <7hdhj6>; lua; dkim_signing.lua:88: Using selector prefix DKIM_SELECTORS for domain senderdomain.com
2018-01-19 15:42:33 #19(normal) <df62ea>; lua; ip_score.lua:312: skip IP Score for local networks and authorized users
2018-01-19 15:42:33 #19(normal) <df62ea>; lua; once_received.lua:82: Skipping once_received for authenticated user or local network
2018-01-19 15:42:33 #19(normal) <7hdhj6>; lua; arc.lua:500: Using selector prefix DKIM_SELECTORS for domain senderdomain.com
2018-01-19 15:42:33 #19(normal) <df62ea>; lua; dmarc.lua:241: skip DMARC checks for local networks and authorized users
2018-01-19 15:42:33 #19(normal) <gqbcyc>; map; rspamd_map_read_cached: http://172.22.1.251:8081/forwardinghosts.php: read map data cached 32 bytes
2018-01-19 15:42:33 #19(normal) <gqbcyc>; map; rspamd_radix_fin: read radix trie of 1 elements: ents=1 tbm=0 lc=1 mem=1k free=0 waste=0
2018-01-19 15:42:33 #19(normal) <7hdhj6>; lua; dkim_signing.lua:91: cannot make request to load DKIM selector for domain senderdomain.com: nil
2018-01-19 15:42:33 #19(normal) <7hdhj6>; lua; arc.lua:503: cannot make request to load DKIM selector for domain senderdomain.com: nil
```

First of all, I think the DKIM checks should not be skipped, because the mails are just forwarded, and not originating from the local network.

Also, it seems like the ARC signature cannot be added, because the DKIM key cannot be found. I think it shouldn't try to find a key for _senderdomain.com_ (which I obviously don't have), but rather for _myname.com_. So IMHO neither the ENVELOPE FROM, nor the HEADER FROM domain should be used, but my own one instead.

### Configuration:

local.d/arc.conf 

```
# If false, messages with empty envelope from are not signed
allow_envfrom_empty = false;
# If true, envelope/header domain mismatch is ignored
allow_hdrfrom_mismatch = false;
# If true, multiple from headers are allowed (but only first is used)
allow_hdrfrom_multiple = true;
# If true, username does not need to contain matching domain
allow_username_mismatch = false;
# If false, messages from authenticated users are not selected for signing
auth_only = false;
# Default path to key, can include '$domain' and '$selector' variables
path = "/data/dkim/keys/$domain.dkim";
# Default selector to use
selector = "mail";
# If false, messages from local networks are not selected for signing
sign_local = true;
# Symbol to add when message is signed
symbol = "ARC_SIGNED";
# Whether to fallback to global config
try_fallback = true;
# Domain to use for DKIM signing: can be "header" or "envelope"
use_domain = "envelope";
# Whether to normalise domains to eSLD
use_esld = false;
# Whether to get keys from Redis
use_redis = false;
# Hash for DKIM keys in Redis
key_prefix = "DKIM_PRIV_KEYS";
# Selector map
selector_prefix = "DKIM_SELECTORS";
```

### Additional information:

Is there any documentation how to succesfully add ARC headers to forwarded mails?

Thanks for your help!

**Comment by chaosmaster** [comment]
I also believe the default setup of ARC pretty much duplicates DKIM.
From my understanding ARC-signing should be done for _INCOMING_ mails after checking.
Unlike DKIM which is done for _OUTGOING_ mails.
Also the fields signed by ARC seem to be the same as for DKIM, I believe they should also differ.
Gmail signs the following headers in ARC:

```
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=content-transfer-encoding:content-language:mime-version:user-agent
         :date:message-id:subject:from:to:dkim-signature
         :arc-authentication-results;
```

Most notably these include **dkim_signature** and **arc-authentication-results**

With the attached patch you can set the following in _local.d/arc.donf_

> sign_received = true;
> use_domain = recipient;


[dkim_sign_tools.patch.txt](https://github.com/vstakhov/rspamd/files/1721040/dkim_sign_tools.patch.txt)

**Comment by pvagner** [comment]
Hello,
I am trying to implement arc with rspamd for my private messages these days.
Originally I have understood arc concept the way @lukas-hetzenecker and @chaosmaster are proposing. However rspamd docs on rspamd arc module indicate only outgoing emails are elligible for arc signing. I have also verified gmail is not adding arc signature to outgoing messages.
Based on all of this I think arc is supposed to help solving the situation where sender1@domain.tld is sending out email to receiver2@domain.tld and receiver2@domain2.tld has configured forwarding that email to destination3@domain3.tld. MTA responsible for domain2.tld verifies SPF and DKIM like normal and then it should do the ARC signing making sure dkim-signature and arc-authentication-results are included in the sign_headers.
Once MTA responsible for domain3.tld receives the message from domain2.tld specific MTA it will verify SPF and DKIM. SPF will fail most likelly DKIM may or may not fail depending on the configuration of domain2.tld MTA (e.g. email lists tend to change the subject header and add a signature). If domain1.tld owner has published a reject DMARC policy in its DNS, domain3.tld MTA should reject the message. However as domain2.tld MTA provided a valid ARC signature it should not reject the message. It's a bit more complicated than this because ARC is designed to work recursivelly even if message passes over multiple indirect hops.

Now some questions:
* Can you please give an example when signing outgoing emails as documented with rspamd arc module is usefull?
* Do you think my understanding of the matter is correct?
* Does the way I am understanding ARC partially negates rspamd documentation on its arc module?
* Is the patch provided by @chaosmaster going to be reviewed and possibly accepted as a possible configuration within rspamd it-self?
* It is possible to configure signing_headers in local.d/dkim.conf. Will these be used for both DKIM and ARC? Is there a way to configure different signing_headers for DKIM and for ARC so we can for example try to duplicate the gmail config? Having dkim-signature and arc-authentication-results headers as a part of DKIM signature is not very usefull I'd say.
* When veryfying incoming messages is arc module adding arc-authentication-results header?

**Comment by chaosmaster** [comment]
@pvagner I have added a Pull Request for this here #2018 

As for the signing_headers in _local_d/dkim.conf_, they seem to be used for both ARC and DKIM.

**Comment by lukas-hetzenecker** [comment]
Thank you for your patch @chaosmaster - I just tried it and mails are forwarded now as expected.
As the patch is already merged, I'll close this ticket. I could achieve the "Expected results" thanks to the patch.
