### ISSUE TITLE
Option to disable web ui auth

### ISSUE THREAD

**Issue by windware** [vstakhov/rspamd#2003]
* [x] WebUI/Usability

### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:

Ubuntu 16.04 Server

### Description (Please provide a descriptive summary of the issue):

I have Apache deployed that provides authentication in front of rspamd web ui and I'd like to disable the authentication provided by rspamd's web ui.

### Steps to reproduce:

- Set apache / nginx to provide reverse proxy to web ui with basic auth.
- Access web ui through apache / nginx

### Expected results:

Web ui does not ask for a password.

### Actual results:

Web ui asks for a password.

**Comment by stephdl** [comment]
Interested also by this NFR, I have also another authentication by a php page with LDAP backend.

Else It would be nice to authenticate by ldap in RSPAMD.

**Comment by stephdl** [comment]
merci @fatalbanana

**Comment by ws-hono** [comment]
I see the commit says.

* [WebUI] Restore passwordless login support (#2003)

but, how can I enable passwordless login?
I'm having a hard time finding how to do that in the document.

**Comment by andryyy** [comment]
It works fine.

**Comment by ws-hono** [comment]
Do you mean by this sentence?

`secure_ip: list or map with IP addresses that are treated as secure so all commands are allowed from these IPs without passwords`

I've added `secure_ip = "127.0.0.1";` in the local.d/worker-controller.inc (in fact, it was already defined in worker-controller.inc), but having a reverse proxy Apache in front of rspamd on the same host still asks for the login password in the web UI.

I see that about `secure_ip` mentioned in [here](https://rspamd.com/doc/faq.html#how-to-use-the-webui-behind-a-proxy-server) that it checks for either `X-Forwarded-For` or `X-Real-IP` to match for the IP, which would mean the client's IP and not the reverse proxy's IP, so it sounds like I have to add my own IP in order to achieve passwordless login but even if I added my own IP, it still shows the login form.

What I'm trying to achieve is to completely remove the password auth as the Apache itself already has basic auth to block any unauthorized access but is it possible to do that?

**Comment by lavoiesl** [comment]
Found a workaround: Set the secure ip to be _everything_:
```apache
# worker-controller.inc

secure_ip = "0.0.0.0/0";
```
