### ISSUE TITLE
cross compilation fails

### ISSUE THREAD

**Issue by Gottox** [vstakhov/rspamd#332]
Host: VoidLinux, Linux 4.1, x86_64
Target: ARMv7hf

Configure / Make output: https://gist.github.com/Gottox/25ddfaaa54e651054fa1

snowball is built for the target platform and therefore cannot be used during cross compilation.

**Comment by vstakhov** [comment]
The problem here is that you need to compile `snowball` using host compiler and everything rest using cross compiler. `snowball` is a sort of processor that converts its own definitions to the C code. Obviously, snowball itself must be compiled using host compiler whilst the sources it produces should use cross compile.

**Comment by Gottox** [comment]
HOSTCC is set to the correct compiler. Nevertheless, it is not used.

**Comment by vstakhov** [comment]
Yes, but rspamd is built using `cmake`. I don't have a single idea how to make it with this build system.

**Comment by Gottox** [comment]
Okay. Seems to be not supported by cmake at all.

**Comment by vstakhov** [comment]
Well, I was told that it's somehow possible to do with 'EXTERNAL_PROJECT', but it seems to be quite complicated to implement.

**Comment by Gottox** [comment]
Worked around by https://github.com/voidlinux/void-packages/commit/f0d0c31ae130aa5cbba1ae9a932629e094dc10a3

**Comment by vstakhov** [comment]
Wow, that's an interesting trick :)
