### ISSUE TITLE
Recovery email

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rspamd#432]
Hello
When an email is lost we will say by rejecting rspamd there opportunity to resend the e-mail in the inbox of the user?

Thank you

Mz

**Comment by moisseev** [comment]
Would you clarify your question?
Email messages should never been lost with properly configured mail systems. If you are using pre-queue filtering, then (since message is not received by recipient's mail system yet) sender's mail system is responsible for handling rejected messages: return  it to sender ( 5.x.x code) or try to resend later (4.x.x code). If you are using after-queue filtering, rejected message should be bounced back to the recipient. Also you can put rejected messages on hold in recipient's mail server queue.

**Comment by MisterM74** [comment]
Clearer
As the subject indicates, RSPamd performs message retrieval

Mz

**Comment by moisseev** [comment]
Actually rspamd doesn't reject messages. It just recommends an action for the MTA. If a message was rejected by MTA during TCP session, it means the message has never been received at all. In other words the MTA refused to receive the message. So we have nothing to restore at recipient's MTA side.

I'm not fully understand what are you trying to achieve. If you want to just mark messages with high scores as spam instead of reject them, you can increase threshold for the `reject` action.

**Comment by vstakhov** [comment]
You can reach that also by storing rejected mail in redis, for example. Rspamd allows to create `post-filters` for these purposes.
