### ISSUE TITLE
URIBL_BLACK sometimes not triggered

### ISSUE THREAD

**Issue by falstaff84** [vstakhov/rspamd#441]
Two identical Spam emails, with identical Received: records (except message ID/date) lead to different X-Spamd-Results:

```
X-Spamd-Result: default: False [12.50 / 20.00]
    RCVD_IN_DNSWL_LOW(0.00)
    FORGED_RECIPIENTS(1.00)
    BAYES_SPAM(4.00)
    URIBL_BLACK(7.50)

X-Spamd-Result: default: False [5.00 / 20.00]
    RCVD_IN_DNSWL_LOW(0.00)
    FORGED_RECIPIENTS(1.00)
    BAYES_SPAM(4.00)
```

**Comment by fatalbanana** [comment]
Did both messages actually contain the listed URI?

Given they do my guess would be that URIBL didn't respond in time (and answer was not already cached at your resolver). Very hard to say what happened with given level of detail.

**Comment by falstaff84** [comment]
I did not feel very comfortable with attaching the raw emails and hence did send the emails to Vsevolod directly. The URL's in the message were all the same, just some IDs were different. I tested the email which has not been detected again, and it gets a lot higher score now. I think that the Blacklist has been updated... However, the upper message which has the URIBL_BLACK score, has been received 2 minutes before the lower message without the URIBL_BLACK score...

**Comment by ameagle** [comment]
Expected reason would be that uribl.com refused your   
query - probably because of excessive queries from your resolver - if   
you're not running your own resolver you probably should. If you are   
running your own resolver you may have to purchase a commercial   
subscription. Refer to http://uribl.com/refused.shtml 

I had the same problem:

root@gk.xxx.ru:/usr/local/etc/rspamd#rspamc spam2.txt
Results for file: spam2.txt (0.969 seconds)
[Metric: default]
Spam: false
Score: 45.74 / 100.00
Action: greylist
Symbol: ABUSE_SURBL (5.50)[treinamentoworkshop.com.multi.surbl.org]
Symbol: BAYES_HAM (-2.75)[98.88%]
Symbol: DATE_IN_PAST (1.00)
Symbol: DBL_SPAM (6.50)[treinamentoworkshop.com.dbl.spamhaus.org]
Symbol: DRUGS_1 (0.00)
Symbol: RE_TEST (10.00)
Symbol: R_LOTTO (8.00)
Symbol: URIBL_BLACK (7.50)[treinamentoworkshop.com.multi.uribl.com]
Symbol: symbol1 (10.00)
Symbol: symbol4 (0.00)
Urls: ["http://treinamentoworkshop.com/e-m="]
Message-ID: 20160118_100347_036112.ao1@xxx.org

root@gk.xxx.ru:/usr/local/etc/rspamd# rspamc spam2.txt
Results for file: spam2.txt (0.286 seconds)
[Metric: default]
Spam: false
Score: 38.24 / 100.00
Action: greylist
Symbol: ABUSE_SURBL (5.50)[treinamentoworkshop.com.multi.surbl.org]
Symbol: BAYES_HAM (-2.75)[98.88%]
Symbol: DATE_IN_PAST (1.00)
Symbol: DBL_SPAM (6.50)[treinamentoworkshop.com.dbl.spamhaus.org]
Symbol: DRUGS_1 (0.00)
Symbol: RE_TEST (10.00)
Symbol: R_LOTTO (8.00)
Symbol: URIBL_BLOCKED (0.00)[treinamentoworkshop.com.multi.uribl.com]
Symbol: symbol1 (10.00)
Symbol: symbol4 (0.00)
Urls: ["http://treinamentoworkshop.com/e-m="]
Message-ID: 20160118_100347_036112.ao1@xxx.org

**Comment by mozzan** [comment]
I have this same problem, too. Rspamd sometimes can get URIBL_BLACK, sometimes not.

But spamassassin always can get  URIBL_BLACK.

Here is the mail
https://www.dropbox.com/s/nvnh6m8zjoq9ow0/uribl_issue.eml?dl=0

rspamd (correct score)
[Metric: default]
Spam: true
Score: 16.30 / 15.00
Action: reject
Symbol: BAYES_SPAM (3.00)[100.00%]
Symbol: DBL_ABUSE_REDIR (1.50)[ppt.cc.dbl.spamhaus.org]
Symbol: DMARC_POLICY_SOFTFAIL (0.10)[flickr.com]
Symbol: FORGED_SENDER (0.30)
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: R_BAD_CTE_7BIT (3.00)
Symbol: R_DKIM_REJECT (1.00)[flickr.com]
Symbol: **URIBL_BLACK (7.50)[ppt.cc.multi.uribl.com]**
Symbol: URIBL_BLOCKED (0.00)[cla.fr.multi.uribl.com]
Message-ID: 20160222054949.B2B4B214A20@scan.sharetech.com.tw

rspamd (failed score)
[Metric: default]
Spam: false
Score: 8.80 / 15.00
Action: add header
Symbol: BAYES_SPAM (3.00)[100.00%]
Symbol: DBL_ABUSE_REDIR (1.50)[ppt.cc.dbl.spamhaus.org]
Symbol: DMARC_POLICY_SOFTFAIL (0.10)[flickr.com]
Symbol: FORGED_SENDER (0.30)
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: R_BAD_CTE_7BIT (3.00)
Symbol: R_DKIM_REJECT (1.00)[flickr.com]
Symbol: **URIBL_BLOCKED (0.00)[ppt.cc.multi.uribl.com]**
Message-ID: 20160222054949.B2B4B214A20@scan.sharetech.com.tw

spamassassin always correct
X-Spam-Report1: 
	*  **2.0 URIBL_BLACK Contains an URL listed in the URIBL blacklist
	*      [URIs: ppt.cc]**
	* -0.7 RCVD_IN_DNSWL_LOW RBL: Sender listed at http://www.dnswl.org/, low
	*      trust
	*      [66.196.81.228 listed in list.dnswl.org]
	* -0.7 RP_MATCHES_RCVD Envelope sender domain matches handover relay domain
	*  0.0 HEADER_FROM_DIFFERENT_DOMAINS From and EnvelopeFrom 2nd level mail
	*      domains are different
	* -0.0 SPF_PASS SPF: sender matches SPF record
	*  0.1 DKIM_SIGNED Message has a DKIM or DK signature, not necessarily
	*      valid
	*  0.0 T_DKIM_INVALID DKIM-Signature header exists but is not valid
	*  2.5 FREEMAIL_FORGED_REPLYTO Freemail in Reply-To, but not From

Anyone can help?
Thanks.

**Comment by fatalbanana** [comment]
`URIBL_BLOCKED` indicates that your resolver is indeed blocked - could be any resolver in `/etc/resolv.conf` (so check all) and could be intermittent. See post immediately above yours for more detail.

FWIW, this is not actually the issue reported in the OP. :)

**Comment by fatalbanana** [comment]
If you can show that your resolver in fact returned something other than `127.0.0.1` when `URIBL_BLOCKED` was triggered then that is in fact an issue. :) (but this seems unlikely)

**Comment by mozzan** [comment]
my /etc/resolv.conf :
nameserver 127.0.0.1
nameserver 168.95.1.1

**Comment by fatalbanana** [comment]
`168.95.1.1` is an open resolver so I'm able to tell you that it's blocked by URIBL:

```
$ host example.com.multi.uribl.com 168.95.1.1
Using domain server:
Name: 168.95.1.1
Address: 168.95.1.1#53
Aliases: 

example.com.multi.uribl.com has address 127.0.0.1
```

**Comment by mozzan** [comment]
Then could I ask why spamassassin doesn't be blocked by URIBL?
Thanks.

**Comment by fatalbanana** [comment]
I don't know - I'm not familiar with SpamAssassin - maybe it uses first entry in `resolv.conf` only.

**Comment by mozzan** [comment]
Why after I removed 168.95.1.1 from resov.conf, it still have this problem?

**Comment by fatalbanana** [comment]
Maybe you didn't restart rspamd (you'd need to do that)? Or your other resolver is blocked too? Or you have resolvers set in rspamd config?

**Comment by mozzan** [comment]
Yes, you are right. This is fine after restarting rspamd.
Could I modify the code where the rspamd using resolve.conf ? Always use first config or use 127.0.0.1 ?

**Comment by fatalbanana** [comment]
You can set nameservers used by rspamd in config: https://rspamd.com/doc/configuration/options.html

**Comment by mnik247** [comment]
You can set DNS server for rspamdin options.inc:
dns {
    timeout = 2s;
    sockets = 16;
    retransmits = 5;
    nameserver = [ "127.0.0.1" ];
}

**Comment by mozzan** [comment]
Problem solved. Thank you for the reply.

**Comment by fatalbanana** [comment]
OP's issue is unclear; more information needed.
