### ISSUE TITLE
Fuzzy: cannot connect to rspamd.com

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#448]
Last rspamd-master build (13.12.2015). Centos 6.7

Dec 13 02:58:37 rspamd[5866]: <>; ; rspamd_inet_address_connect: connect failed: 101, 'Network is unreachable'
Dec 13 02:58:37 rspamd[5866]: <3c9149>; task; register_fuzzy_client_call: cannot connect to rspamd.com, 101, Network is unreachable

If set bare IP in fuzzy_check.conf - no error:
servers = "5.9.155.182:11335"

This is bug?

**Comment by vstakhov** [comment]
Actually, that is ipv6 misconfiguration in your system. Your resolver can return AAAA records but there is no ipv6 route available. In the recent git versions, rspamd can detect and avoid misconfigured addresses. However, the first request can still fail due to ipv6 failure but all subsequent request should be sent using the correct address.

**Comment by AlexeySa** [comment]
I use latest git version. Rspamd write connection error for each incoming message (is not first only). Can this be fixed?

**Comment by vstakhov** [comment]
OK, I'll check that soon.

**Comment by vstakhov** [comment]
I can't reproduce your problem with the recent git. On first call to `rspamd.com` I can observe the erorr:

    2015-12-13 23:28:45 #29925(normal) rspamd_inet_address_connect: connect failed: 65, 'No route to host'
    2015-12-13 23:28:45 #29925(normal) <f50f1c>; task; register_fuzzy_client_call: cannot connect to rspamd.com, 65, No route to host

However, this error disappears after this message.

**Comment by fatalbanana** [comment]
Issue here was that IPv6 address for rspamd.com was not forwarded to fuzzy server AFAICR (it was resolved).
