### ISSUE TITLE
Messages from AquaMail trigger FORGED_MUA_THUNDERBIRD_MSGID_UNKNOWN

### ISSUE THREAD

**Issue by fatalbanana** [vstakhov/rspamd#474]
Reported by @xpunkt.

It sets a user-agent like this:

`User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:24.0) Gecko/20100101 Thunderbird/24.6.0 AquaMail/1.6.0.6 (build: 24000011)`

Note: running on non-x86_64 platform: text appears to have been copied from elsewhere.

... And no Message-Id.

**Comment by kmansoft** [comment]
AquaMail developer here.

First, sending User-ID _is_ enabled by default. To check / enable:

Please long press the account -> options and folders -> composing and sending.

Enable "Send Message-ID" (it is enabled by default, though).

Second, an explanation about Mozilla and Thunderbird and all that.

The reason is Apple's mail service.

Without this user-agent, any messages sent by AquaMail were just "disappearing", no error, just "gone".

No bounce, no error, just "disappear".

As soon as I added a user-agent which looked like a well known mail app, sent messages started getting though.

So it appears that Apple has some sort of "whitelist" of mail apps.

**Comment by fatalbanana** [comment]
@xpunkt - please check your client settings and re-test.

@kmansoft - thank you very much for your input. I can't say I approve of such user-agent spoofing but I do understand.
