### ISSUE TITLE
rspamd not running lua file.

### ISSUE THREAD

**Issue by palashahuja** [vstakhov/rspamd#526]
I just wanted to know whether the --test-lua option of rspamd executable is working or not, because there is no option inside rspamadm that specifies the lua files that it is supposed to run. Also, I wanted to know if anyone is working on this ?

**Comment by vstakhov** [comment]
That has been broken long ago and not used by anybody since that. Anyway, `rspamd` now does not perform such an actions on it's own - these functions are moved to `rspamadm` command. Lua testing is still argueable feature, therefore I've not ressurected it and I'm not sure if I would. 

Why do you need this function by the way?

**Comment by palashahuja** [comment]
@vstakhov, I guess, it would be better to remove this feature altogether from the code base. Also, we could remove this page [https://rspamd.com/doc/workers/lua_worker.html](url)

**Comment by vstakhov** [comment]
Ok, I've updated description that this option is no longer supported. Documentation page won't be removed as HTTP `404` error page is worse than 'work in progress'.
