### ISSUE TITLE
Documentation issues/questions

### ISSUE THREAD

**Issue by rpv-tomsk** [vstakhov/rspamd#883]
### Rspamd `Greylisting module` and `rmilter greylisting` feature;
- It documented what I have to enable Rspamd greylisting module manually by defining empty configuration.  I have no `greylist` section configured in rspamd, but greylisting works.
-  Is that are indepenent components? It not so clear what Rmilter does no greylisting without instruction from Rspamd.
- Both components has `expire` and `timeout` options. Which one will have precedency?
- Greylisting module has option `key_prefix: prefix for hashes to store in Redis (rg by default)`. Rmilter has `grey_prefix: used for greylisting records` in Redis section.  How to deal with them? Should their values be equal?
- At https://rspamd.com/doc/modules/greylisting.html page there is "This module is intended to delay messages that have spam score above `greylisting` action threshold."
  But configuration option is `greylist`. 

```
actions {
      ...
      greylist = 4;
    }
```

As `greylisting` is highlighted, it can be treated as configuration option.
Propose to remove highlighting or replace `greylisting` by `greylist`.
- Is Rspamd `Greylisting module` intended to be  used in setups without rmilter ?
### Rspamd `ratelimit plugin` and `rmilter rate limits` (rmilter limits section).

  As I understand, these are indepenent components and Rmilter can do rate limit yourself, without Rspamd. I'm correct?
  So, there is no reasons to use Rspamd ratelimit plugin with `rmilter ratelimits` both (except when Rspamd `symbol` option is configured). 

  As I understand, the main differences are:
    - Rmilter can delay message on early stages (RCPT TO)
    - Rspamd plugin can set symbol based on limits and that is it's main purpose.

  May be it needs to be explicitly stated in docs:
- That Rmilter can delay message on early stages (RCPT TO) as opposed to Rspamd;
- If these components are using same storage or not;
- That there is no need to use `Rspamd ratelimit plugin` without `symbol` when setup uses `rmilter`;
- That these components can be used for different goals, so they can have different limits configured;
### Remarks about https://rspamd.com/doc/modules/ratelimit.html
- Example in page bottom has zero burst in config and non-zero burst value in comments. It can be confusing.
- Can a message for temporary rejection reason be configured?
- "the value is scaled as , where tanh is the hyperbolic tanhent function". 
  I see nothing after 'as', `<script type="math/tex">` was not processed/displayed correctly (my browser is FF 48 on win).
- Commented configuration option 'servers'  may be added as example in modules.d/ratelimit.conf.
  It may be unclear for people if can we use the same redis server as other parts of rspamd and rmilter or not.
  Link to https://rspamd.com/doc/configuration/redis.html may be added.
- The page says: `In the default configuration, there are no cache servers specified, hence, the module won’t work unless you add this option to the configuration.`.  
  But on https://rspamd.com/doc/configuration/redis.html there is an example `disabled_modules = ["ratelimit"];`  and the following comment:
  `This configuration snippet denies ratelimit to use the common Redis configuration and this module will be disabled if Redis is not explicitly configured for this module (either in redis -> ratelimit section or in ratelimit section).`
  These two pages are contrary to each other. Will `ratelimit` module use default configured Redis server or not?

**Comment by fatalbanana** [comment]
Yes- there are separate greylisting implementations in rspamd/rmilter (more recently in the former, and since some while in the latter). You're likely using rmilter's greylisting which is on by default (rspamd's greylisting is off by default). It's advisable to configure one & not both. Rmilter can work with rspamd's greylisting too.

Rspamd's greylisting actually effects messages above `no action` threshold (including `greylist`).

**Yes** rspamd's greylisting is intended for setups **without** rmilter.

----

Yes there are ratelimit implementations in both Rspamd & Rmilter.

Rspamd could apply ratelimits at RCPT stage but integration layer (Rmilter) would have to support that.

----

Yes burst rates in comments are confusing, they should not be there or configuration should be adjusted to match.

Yes- formula may not be visible.

Yes- this page could be updated to tell about global redis confiruation.

_If_ there is a global redis server specified, ratelimit module will use that, _unless_ it's added to `disabled_modules` or one was configured in `servers` (all modules using redis are working this way).

Pull requests welcome. Docs live here: https://github.com/vstakhov/rspamd.com/
